build: Report junit in CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -75,7 +75,13 @@ jobs:
         run: grep -c "warning:" ${{github.workspace}}/build/build.log
 
       - name: Test
-        run: ctest --test-dir ${{github.workspace}}/build
+        run: ctest -Q --test-dir ${{github.workspace}}/build --output-junit ${{github.workspace}}/build/report.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: ${{github.workspace}}/build/report.xml
 
   linters:
     if: false
